import { useMemo, useState } from "react";
import { BarChart3, Check, ChevronDown, ClipboardList, Clock3, IndianRupee, LayoutDashboard, LogOut, Menu, MoreHorizontal, Printer, QrCode, RefreshCw, ShieldAlert, ShieldCheck, ToggleLeft, ToggleRight, Users, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { hasStaffRole, rupees } from "@shared/cinebites";
import ShiftSummary from "@/pages/ShiftSummary";
import StaffManagement from "@/pages/StaffManagement";
import SessionLinks from "@/pages/SessionLinks";
import SeatQrGenerator from "@/pages/SeatQrGenerator";

type Tab = "overview" | "shift" | "orders" | "menu" | "refunds" | "staff" | "sessions" | "seatQrs" | "audit";
const tabs: { id: Tab; label: string; icon: typeof LayoutDashboard }[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "shift", label: "Shift summary", icon: Clock3 }, { id: "orders", label: "Orders", icon: ClipboardList }, { id: "menu", label: "Menu", icon: Menu }, { id: "refunds", label: "Refunds", icon: WalletCards }, { id: "staff", label: "Staff & devices", icon: Users }, { id: "sessions", label: "QR sessions", icon: QrCode }, { id: "seatQrs", label: "Seat QR stickers", icon: Printer }, { id: "audit", label: "Audit log", icon: ShieldCheck },
];

export default function Admin() {
  const { user, logout, loading } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/login?redirect=/admin" });
  const [tab, setTab] = useState<Tab>("overview");
  const stats = trpc.admin.stats.useQuery();
  const orders = trpc.admin.orders.useQuery();
  const menu = trpc.admin.menu.useQuery();
  const audit = trpc.admin.audit.useQuery();
  const availability = trpc.admin.setAvailability.useMutation({ onSuccess: () => menu.refetch(), onError: (error) => toast.error(error.message) });
  const refund = trpc.admin.refundPreview.useMutation({ onSuccess: () => toast("Refund request logged for review", { description: "Provider execution remains admin-controlled." }) });
  const today = new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "2-digit", month: "short" }).format(new Date());
  if (loading) return <div className="staff-loading-screen"><span className="button-spinner" /> Checking admin access…</div>;
  if (!user || !hasStaffRole(user.role, ["OWNER_ADMIN", "ADMIN", "MANAGER"])) {
    return (
      <div className="staff-loading-screen">
        <ShieldAlert size={20} />
        <div>
          <strong>Admin access restricted</strong>
          <span>Your account does not have admin privileges.</span>
          <div className="mt-3 flex gap-3 text-sm">
            <Link href="/login" className="text-orange-400 underline">Sign in with Admin Google Account</Link>
            <Link href="/kitchen" className="text-white/60 underline">Kitchen view</Link>
          </div>
        </div>
      </div>
    );
  }
  return <div className="admin-app"><aside className="admin-sidebar"><div className="admin-logo"><div className="staff-brand-mark"><BarChart3 size={17} /></div><div><strong>cine<span>bites</span></strong><small>Admin Console</small></div></div><div className="admin-nav-label">Manage</div><nav>{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`admin-nav-item ${tab === id ? "active" : ""}`}><Icon size={16} />{label}{id === "refunds" && <span className="nav-badge">1</span>}</button>)}</nav><div className="admin-sidebar-bottom"><div className="admin-live"><span /> Service live</div><Link href="/kitchen" className="kitchen-link">Open kitchen view <ChevronDown size={14} /></Link><button className="admin-user" onClick={() => logout()}><span className="avatar-circle">{user?.name?.charAt(0) || "A"}</span><span><strong>{user?.name || "Owner Admin"}</strong><small>Owner admin</small></span><LogOut size={14} /></button></div></aside><main className="admin-content"><header className="admin-topbar"><div><p className="admin-kicker">Bhubaneswar • Screen service</p><h1>{tabs.find((item) => item.id === tab)?.label}</h1></div><div className="admin-top-actions"><span className="admin-date">{today}</span><button className="refresh-button" onClick={() => { stats.refetch(); orders.refetch(); menu.refetch(); }}><RefreshCw size={14} /> Refresh</button></div></header>{tab === "overview" && <Overview stats={stats.data} orders={orders.data} />}{tab === "shift" && <ShiftSummary />}{tab === "orders" && <OrdersTable orders={orders.data ?? []} onRefund={(orderId, amount) => refund.mutate({ orderId, amountPaise: amount, reason: "Exceptional refund review" })} />}{tab === "menu" && <MenuManager items={menu.data ?? []} onToggle={(id, available) => availability.mutate({ id, available })} />}{tab === "refunds" && <Refunds />}{tab === "staff" && <StaffManagement />}{tab === "sessions" && <SessionLinks />}{tab === "seatQrs" && <SeatQrGenerator />}{tab === "audit" && <Audit logs={audit.data ?? []} />}</main></div>;
}

function Overview({ stats, orders }: { stats?: { ordersToday: number; revenuePaise: number; pending: number; preparing: number; ready: number; delivered: number; paymentFailures: number; popularItem: string }; orders?: { id: string; orderNumber: string; status: string; screen: string; seat: string; customerName: string; totalPaise: number; createdAt: string }[] }) {
  const cards = [{ label: "Revenue today", value: stats ? rupees(stats.revenuePaise) : "—", icon: IndianRupee, tone: "peach" }, { label: "Orders today", value: stats?.ordersToday ?? "—", icon: ClipboardList, tone: "violet" }, { label: "In kitchen", value: stats ? stats.pending + stats.preparing : "—", icon: ChefIcon, tone: "green" }, { label: "Ready to deliver", value: stats?.ready ?? "—", icon: Check, tone: "amber" }];
  return <><div className="stat-grid">{cards.map(({ label, value, icon: Icon, tone }) => <div className={`stat-card ${tone}`} key={label}><div className="stat-card-top"><span>{label}</span><Icon size={16} /></div><strong>{value}</strong><small>{label === "Revenue today" ? "+12.4% vs last Friday" : label === "Orders today" ? "21 already delivered" : "Live from kitchen queue"}</small></div>)}</div><div className="admin-grid-two"><section className="admin-panel"><div className="panel-heading"><div><p className="admin-kicker">Live operations</p><h2>Order flow today</h2></div><span className="live-dot-label"><span /> Live</span></div><div className="flow-chart"><div className="chart-bar"><span style={{ height: "38%" }} /><span style={{ height: "52%" }} /><span style={{ height: "48%" }} /><span style={{ height: "72%" }} /><span style={{ height: "64%" }} /><span style={{ height: "86%" }} /><span style={{ height: "74%" }} /><span style={{ height: "95%" }} /></div><div className="chart-labels"><span>12 PM</span><span>2 PM</span><span>4 PM</span><span>6 PM</span><span>Now</span></div></div></section><section className="admin-panel"><div className="panel-heading"><div><p className="admin-kicker">Top performer</p><h2>Popular items</h2></div><BarChart3 size={18} className="panel-muted" /></div><div className="popular-list"><PopularItem rank="01" name={stats?.popularItem || "Masala Popcorn"} detail="42 orders" progress="86%" /><PopularItem rank="02" name="Big Screen Combo" detail="31 orders" progress="68%" /><PopularItem rank="03" name="Loaded Nachos" detail="24 orders" progress="52%" /></div></section></div><section className="admin-panel recent-panel"><div className="panel-heading"><div><p className="admin-kicker">Latest activity</p><h2>Recent orders</h2></div><button onClick={() => toast("Full order history is available in Orders")}>View all <ChevronDown size={14} /></button></div><div className="recent-list">{(orders ?? []).slice(0, 3).map((order) => <div className="recent-row" key={order.id}><span className="recent-order-number">{order.orderNumber}</span><span>{order.customerName} • {order.screen} {order.seat}</span><span className={`status-pill ${order.status.toLowerCase()}`}>{order.status}</span><strong>{rupees(order.totalPaise)}</strong></div>)}</div></section></>;
}
function ChefIcon() { return <span className="chef-icon">⌁</span>; }
function PopularItem({ rank, name, detail, progress }: { rank: string; name: string; detail: string; progress: string }) { return <div className="popular-row"><span className="popular-rank">{rank}</span><div className="popular-main"><strong>{name}</strong><div className="popular-progress"><span style={{ width: progress }} /></div></div><span>{detail}</span></div>; }

function OrdersTable({ orders, onRefund }: { orders: { id: string; orderNumber: string; status: string; screen: string; seat: string; customerName: string; phoneLast4: string; totalPaise: number; source: string; paymentStatus: string; createdAt: string }[]; onRefund: (id: string, amount: number) => void }) { return <section className="admin-panel table-panel"><div className="table-toolbar"><div><p className="admin-kicker">Privacy-safe order management</p><h2>All orders</h2></div><div className="table-filters"><button>Today <ChevronDown size={13} /></button><button>All statuses <ChevronDown size={13} /></button></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Customer / seat</th><th>Status</th><th>Payment</th><th>Total</th><th /></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</small></td><td><strong>{order.customerName}</strong><small>{order.screen} • {order.seat} • •••• {order.phoneLast4}</small></td><td><span className={`status-pill ${order.status.toLowerCase()}`}>{order.status}</span></td><td><span className="paid-label"><Check size={12} /> {order.paymentStatus}</span></td><td><strong>{rupees(order.totalPaise)}</strong><small>{order.source}</small></td><td><button className="row-menu" onClick={() => onRefund(order.id, order.totalPaise)} title="Log refund review"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table></div></section>; }

function MenuManager({ items, onToggle }: { items: { id: string; name: string; category: string; pricePaise: number; description: string; available: boolean; options: string[] }[]; onToggle: (id: string, available: boolean) => void }) { return <section className="admin-panel table-panel"><div className="table-toolbar"><div><p className="admin-kicker">Catalog controls</p><h2>Menu availability</h2></div><button className="primary-small" onClick={() => toast("Menu item editor is ready for the next menu import")}>+ Add menu item</button></div><div className="menu-manage-list">{items.map((item) => <div className="menu-manage-row" key={item.id}><div className="menu-thumb">{item.name.slice(0, 1)}</div><div className="menu-manage-copy"><strong>{item.name}</strong><span>{item.category} • {rupees(item.pricePaise)} • {item.options.length} add-ons</span></div><span className={`availability-label ${item.available ? "available" : "unavailable"}`}>{item.available ? "Available" : "Sold out"}</span><button onClick={() => onToggle(item.id, !item.available)} className="toggle-button" aria-label={`Toggle ${item.name}`}>{item.available ? <ToggleRight size={25} /> : <ToggleLeft size={25} />}</button></div>)}</div></section>; }
function Refunds() { return <section className="admin-panel empty-admin-panel"><div className="empty-admin-icon"><WalletCards size={22} /></div><p className="admin-kicker">Exceptional only</p><h2>Refund approvals</h2><p>Refunds never start in the kitchen. They are reviewed here by Admin, recorded with a reason, and matched to a provider refund ID.</p><button className="secondary-admin-button" onClick={() => toast("Select an order from Orders to create a refund review")}>Review an order <ChevronDown size={14} /></button></section>; }
function Staff() { return <section className="admin-panel empty-admin-panel"><div className="empty-admin-icon"><Users size={22} /></div><p className="admin-kicker">Access control</p><h2>Staff & devices</h2><p>Individual staff accounts, role-based access, approved devices, daily PINs, and 2FA-ready metadata live here.</p><div className="role-list"><span>OWNER_ADMIN</span><span>ADMIN</span><span>MANAGER</span><span>KITCHEN</span><span>CASHIER</span><span>READ_ONLY</span></div><button className="secondary-admin-button" onClick={() => toast("Staff invitation flow is ready for provider setup")}>Invite staff member <ChevronDown size={14} /></button></section>; }
function Audit({ logs }: { logs: { id: string; action: string; detail: string; actor: string; createdAt: string }[] }) { return <section className="admin-panel table-panel"><div className="table-toolbar"><div><p className="admin-kicker">Sensitive actions</p><h2>Audit log</h2></div><span className="audit-safe"><ShieldCheck size={14} /> Redacted by default</span></div><div className="audit-list">{logs.map((log) => <div className="audit-row" key={log.id}><span className="audit-icon"><ShieldCheck size={13} /></span><div><strong>{log.action}</strong><p>{log.detail}</p></div><span className="audit-meta">{log.actor}<br />{new Date(log.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>)}</div></section>; }
